before_install:
  - gem install cocoapods

before_script:
  - cp 'Mobile Wired/TestFlightTokens-Sample.h' 'Mobile Wired/TestFlightTokens.h'

language: objective-c
xcode_sdk: iphonesimulator7.1
xcode_workspace: Mobile Wired.xcworkspace